all:
	cd smr && $(MAKE) $@
	cd replicator && $(MAKE) $@
	cd test && $(MAKE) $@

clean:
	cd smr && $(MAKE) $@
	cd replicator && $(MAKE) $@
	cd test && $(MAKE) $@

gcov:
	cd smr && $(MAKE) $@
	cd replicator && $(MAKE) $@
	cd test && $(MAKE) $@

test:

